### ISSUE TITLE
Missing GeneralConverter for Option[Long]

### ISSUE THREAD

**Issue by agarbutt** [marklister/product-collections#26]
There is no provided GeneralConverter for Option[Long], while one can be provided, this seems like an oversight. 

Error:(22, 23) could not find implicit value for parameter c2: com.github.marklister.collections.io.GeneralConverter[Option[Long]]
      parser.parseFile(filePath, delimiter = ",", hasHeader = true)
                      ^

**Comment by marklister** [comment]
Yeah, that's an oversight.  I'll fix it sometime or fast track a pull request while I'm on holiday.

**Comment by marklister** [comment]
Yeah, that's an oversight.  I'll fix it sometime or fast track a pull request while I'm on holiday.

**Comment by marklister** [comment]
A possible work around is something like implicit val optLong = longConverter.toOption

Will only work with master as I changed the converters recently.

**Comment by marklister** [comment]
Commit 7a22c99 fixes.

**Comment by agarbutt** [comment]
Thanks. Sorry I didn't have a chance to make a pull request. I know it was an easy one and the work around was easy to come up with given your documentation.

**Comment by marklister** [comment]
Glad the documentation fulfilled its purpose.  I did a full overhaul of all the converters and added a test to prevent missing converters in future.  I'm working on getting a working scala js version before I push out a release.
