### ISSUE TITLE
Add a way to drop header rows when parsing CSV.

### ISSUE THREAD

**Issue by ClintCombs** [marklister/product-collections#28]
Is there an existing mechanism to drop a header row when parsing CSV files? If not, what do you think is the most effective option for adding this?

**Comment by marklister** [comment]
There's a parameter `hasHeader:Boolean` eg:

CsvParser[Int,String].parse(reader=.... , hasHeader==true)

I'm sorry I'm busy updating the doc for v1.4.0

Here's the [scaladoc for v1.3.0](http://marklister.github.io/product-collections/target/scala-2.10/api/#com.github.marklister.collections.io.CsvParser1)

**Comment by marklister** [comment]
The [old README](https://github.com/marklister/product-collections/blob/master/README-old.md) is correct doc to read for v1.3.0.  Sorry about the flux.

**Comment by ClintCombs** [comment]
Thanks, that's what I needed!
