### ISSUE TITLE
Allow carriage return as end-of-line character

### ISSUE THREAD

**Issue by wongelz** [marklister/product-collections#37]
Can we add support for CSV files that use carriage returns (\r) as line separator? Currently the entire file contents are concatenated into the first row.

**Comment by marklister** [comment]
Not at my computer today.  You could probably fix this by a small change in `InputBuffer`

Of no luck I'll have a look later this week.

**Comment by marklister** [comment]
As I recall it has an eol function.  You could widen the scope.

**Comment by marklister** [comment]
Thanks!
