### ISSUE TITLE
1.4.3 artifacts for Scala 2.10.6

### ISSUE THREAD

**Issue by nrinaudo** [marklister/product-collections#39]
Is there a particular reason for 1.4.3 artifacts not to be published for Scala 2.10.6? It seems to be the first release not to be backward compatible.

**Comment by marklister** [comment]
Probably an oversight, I'll have a look

**Comment by marklister** [comment]
Thanks for reporting, should reflect on maven central soon.

**Comment by nrinaudo** [comment]
Thanks for dealing with this so quickly!
