### ISSUE TITLE
publish for scala 2.13.0-M5

### ISSUE THREAD

**Issue by pjfanning** [marklister/product-collections#48]
Would it be possible to release a scala 2.13.0-M5 compatible jar?

**Comment by marklister** [comment]
I'll have a look tomorrow...

**Comment by marklister** [comment]
https://www.scala-lang.org/blog/2017/02/28/collections-rework.html just for reference

**Comment by marklister** [comment]
See pull request #49

**Comment by marklister** [comment]
I had a look and this is out of scope for me at present.  Scala 2.13 has a total collections redesign and product-collections relies on many design features of the old design, particularly CanBuildFrom and friends.  I based product-collections very closely on an original article which explained the old design.  It's too much work right now and I'd need to dig through the source code, ask silly questions on the various fora etc to figure it out.  If at some future date if there's a detailed explanation of how the various collections classes fit together I might give it a go.

Pull requests welcome!
